sudo: true
language: ruby
rvm:
  - 2.2.5
  - 2.3.1
  - rbx
  - jruby-9

before_install:
  - rvm get head
  - rvm reload
  - rvm use --install $TRAVIS_RUBY_VERSION --binary --latest
install:
  - gem install bundler
  - bundle install --retry=3
  - gem install yahns unicorn rainbows zbatery puma thin torquebox trinidad || true
script: 'rake test'
