sudo: false
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.0
  - rbx
  - jruby-9

before_install:
  - rvm get head
  - rvm reload
  - rvm use --install $TRAVIS_RUBY_VERSION --binary --latest
install:
  - gem install bundler
  - bundle install --retry=3
  - gem install yahns zbatery rainbows unicorn puma thin torquebox trinidad || true
script: 'rake test'
